### ISSUE TITLE
react-native-localization-settings is failing to build after updating from Expo 50 to 51

### ISSUE THREAD

**Issue by 7ammer** [jakex7/react-native-localization-settings#11]
Hello

[react-native-localization-settings](https://github.com/jakex7/react-native-localization-settings) is failing to build with Expo 51.

Relevant package versions:
* react-native-localization-settings 1.0.2
* react-native 0.74.1
* react 18.2.0
* expo 51.0.2

Relevant error message:
```
UnsupportedModulePropertyParserError: Module NativeLocalizationSettings: TypeScript interfaces extending TurboModule must only contain 'FunctionTypeAnnotation's. Property 'language' refers to a 'TSStringKeyword'.
```

Terminal log:

```
$ APP_ENV=development expo prebuild --clean --platform ios && expo run:ios --device

✔ Cleared ios code
✔ Created native directory
✔ Updated package.json | no changes
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: [!] /Users/jambo/.nvm/versions/node/v20.12.2/bin/node ./../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/ios/.. -o /Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/ios -t ios

[Codegen] Analyzing /Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/package.json
[Codegen] Searching for codegen-enabled libraries in the app.
[Codegen] The "codegenConfig" field is not defined in package.json. Assuming there is nothing to generate at the app level.
[Codegen] Searching for codegen-enabled libraries in the project dependencies.
[Codegen] Found @react-native-community/datetimepicker
[Codegen] Found @react-native-picker/picker
[Codegen] Found react-native
[Codegen] Found react-native-gesture-handler
[Codegen] Found react-native-localization-settings
[Codegen] Found react-native-localize
[Codegen] Found react-native-mmkv
[Codegen] Found react-native-pager-view
[Codegen] Found react-native-reanimated
[Codegen] Found react-native-safe-area-context
[Codegen] Found react-native-screens
[Codegen] Found react-native-svg


[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
[Codegen] Processing RNDateTimePickerCGen
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, visionos for RNDateTimePickerCGen
[Codegen] Processing rnpicker
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos for rnpicker
[Codegen] Processing FBReactNativeSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing rncore
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing rngesturehandler_codegen
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rngesturehandler_codegen
[Codegen] Processing RNLocalizationSettingsSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios for RNLocalizationSettingsSpec
[Codegen] Done.
UnsupportedModulePropertyParserError: Module NativeLocalizationSettings: TypeScript interfaces extending TurboModule must only contain 'FunctionTypeAnnotation's. Property 'language' refers to a 'TSStringKeyword'.
at throwIfModuleTypeIsUnsupported (/Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/error-utils.js:163:11)
at buildPropertySchema (/Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:472:3)
at /Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:705:24
at guard (/Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/utils.js:26:14)
at /Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:702:14
at Array.map (<anonymous>)
at buildModuleSchema (/Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:699:6)
at /Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:522:9
at guard (/Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/utils.js:26:14)
at buildSchemaFromConfigType (/Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:521:22) {
nodes: [ undefined ]
}
.

#  from /Users/jambo/Documents/Projects/24-7prayer/my-app/6.Application/my-app/ios/Podfile:26
#  -------------------------------------------
#  
>    use_react_native!(
#      :path => config[:reactNativePath],
#  -------------------------------------------

pod install --repo-update --ansi exited with non-zero code: 1

```

**Comment by 7ammer** [comment]
I'm not very good with building plugins but based on the error message it looks like this is what is causing the issue: https://github.com/jakex7/react-native-localization-settings/blob/cd294822f7810a5cef31cb2856a43e0824f4961b/src/NativeLocalizationSettings.ts#L7

It appears that TurboModule only allows for functions (FunctionTypeAnnotation) which means `language: string` is not allowed.

**Comment by 7ammer** [comment]
Closing as this is a duplicate of: https://github.com/jakex7/react-native-localization-settings/issues/5

**Comment by a-eid** [comment]
@7ammer wondering if you guys written an expo plugin for it yet ?
